// ══════════════════════════════════════
// PRODUCT DATA
// ══════════════════════════════════════

const PRODUCTS = [
  {
    id: 1,
    name: 'Car Hoodie',
    collection: 'Drop 01 · Foundation',
    price: 249,
    badge: 'limited',
    badgeText: 'Limited',
    stock: 5,
    sizes: ['XS','S','M','L','XL','XXL'],
    unavail: [],
    category: 'drop01',
    desc: 'For those who live behind the wheel and dress like it. Heavyweight fleece hoodie with automotive graphic print. Oversized fit, dropped shoulders, ribbed cuffs.',
    fabric: '400gsm cotton/polyester blend',
    care: 'Cold wash, hang dry, iron inside-out',
    ph: 'CAR\nHOODIE',
    color: '#1a1a1a',
    img: 'images/products/car_hoodie_1.jpg',
    imgs: [
      'images/products/car_hoodie_3.jpg',
      'images/products/car_hoodie_2.jpg',
    ]
  },
  {
    id: 2,
    name: 'Arabic Print Tee',
    collection: 'Drop 01 · Foundation',
    price: 149,
    badge: 'new',
    badgeText: 'New',
    stock: 15,
    sizes: ['XS','S','M','L','XL','XXL'],
    unavail: [],
    category: 'drop01',
    desc: 'Arabic calligraphy meets UAE streetwear. 230gsm heavyweight cotton tee with bold Arabic-script screen print. Boxy silhouette, double-stitched seams.',
    fabric: '230gsm 100% ringspun cotton',
    care: 'Cold wash, tumble dry low',
    ph: 'ARABIC\nTEE',
    color: '#1a1207',
    img: 'images/products/arabic_print_tshirt_1.jpg',
    imgs: [
      'images/products/arabic_print_tshirt_1.jpg',
      'images/products/arabic_print_tshirt_2.jpg',
    ]
  },
  {
    id: 3,
    name: 'Brown Spider Hoodie',
    collection: 'Drop 01 · Foundation',
    price: 269,
    badge: 'limited',
    badgeText: 'Limited',
    stock: 4,
    sizes: ['S','M','L','XL','XXL'],
    unavail: [],
    category: 'drop01',
    desc: 'Eight legs, one statement. Heavy fleece hoodie with spider web graphic across the back. Earth-tone colourway built for the UAE winter streets.',
    fabric: '380gsm cotton/polyester fleece',
    care: 'Cold wash, hang dry',
    ph: 'SPIDER\nHOODIE',
    color: '#2a1f12',
    img: 'images/products/brown_spider_hoodie_1.jpg',
    imgs: [
      'images/products/brown_spider_hoodie_1.jpg',
      'images/products/brown_spider_hoodie_2.jpg',
      'images/products/brown_spider_hoodie_3.jpg',
    ]
  },
  {
    id: 4,
    name: 'Clock Tee',
    collection: 'Drop 01 · Foundation',
    price: 159,
    badge: 'new',
    badgeText: 'New',
    stock: 18,
    sizes: ['XS','S','M','L','XL','XXL'],
    unavail: [],
    category: 'drop01',
    desc: 'Time is the only currency that matters. Oversized tee with large clock graphic print. 230gsm heavyweight cotton. Relaxed fit, pre-washed for softness.',
    fabric: '230gsm 100% cotton',
    care: 'Cold wash, tumble dry low',
    ph: 'CLOCK\nTEE',
    color: '#0d0d0d',
    img: 'images/products/clock_tshirt_1.png',
    imgs: [
      'images/products/clock_tshirt_1.png',
      'images/products/clock_tshirt_2.png',
    ]
  },
  {
    id: 5,
    name: 'Dragon Logo Tee',
    collection: 'Drop 01 · Foundation',
    price: 149,
    badge: 'new',
    badgeText: 'New',
    stock: 20,
    sizes: ['XS','S','M','L','XL','XXL'],
    unavail: [],
    category: 'drop01',
    desc: 'East meets UAE. Dragon logo tee with embroidered chest detail and screen-back graphic. 230gsm ringspun cotton, boxy cut.',
    fabric: '230gsm 100% ringspun cotton',
    care: 'Cold wash, tumble dry low',
    ph: 'DRAGON\nTEE',
    color: '#1a0a0a',
    img: 'images/products/dragon_logo_tshirt_1.jpg',
    imgs: [
      'images/products/dragon_logo_tshirt_1.jpg',
    ]
  },
  {
    id: 6,
    name: 'Eye Logo Tee',
    collection: 'Drop 01 · Foundation',
    price: 149,
    badge: 'limited',
    badgeText: 'Limited',
    stock: 8,
    sizes: ['XS','S','M','L','XL','XXL'],
    unavail: ['XS'],
    category: 'drop01',
    desc: 'Always watching. The eye sees through cultures, through borders. Minimal graphic tee with bold eye logo print. 230gsm cotton, relaxed street fit.',
    fabric: '230gsm 100% cotton',
    care: 'Cold wash, hang dry',
    ph: 'EYE\nTEE',
    color: '#0a0a1a',
    img: 'images/products/eye_logo_tshirt.jpg',
    imgs: [
      'images/products/eye_logo_tshirt.jpg',
    ]
  },
  {
    id: 7,
    name: 'Game Hoodie',
    collection: 'Drop 01 · Foundation',
    price: 259,
    badge: 'new',
    badgeText: 'New',
    stock: 10,
    sizes: ['S','M','L','XL','XXL'],
    unavail: [],
    category: 'drop01',
    desc: 'Life is a game. Play it in this. Gaming-inspired graphic hoodie with controller motifs and pixel art details. Heavyweight fleece, oversized fit.',
    fabric: '400gsm cotton/polyester blend',
    care: 'Cold wash, hang dry',
    ph: 'GAME\nHOODIE',
    color: '#0d1a0d',
    img: 'images/products/game_hoodie.jpg',
    imgs: [
      'images/products/game_hoodie.jpg',
    ]
  },
  {
    id: 8,
    name: 'Ghost Hoodie',
    collection: 'Drop 01 · Foundation',
    price: 269,
    badge: 'limited',
    badgeText: 'Limited',
    stock: 3,
    sizes: ['S','M','L','XL','XXL'],
    unavail: [],
    category: 'drop01',
    desc: 'Move silent. Ghost graphic hoodie with oversized back print and tonal embroidery on chest. The most limited piece in Drop 01.',
    fabric: '400gsm cotton/polyester fleece',
    care: 'Cold wash, hang dry, iron inside-out',
    ph: 'GHOST\nHOODIE',
    color: '#141414',
    img: 'images/products/ghost_hoodie_1.jpg',
    imgs: [
      'images/products/ghost_hoodie_1.jpg',
      'images/products/ghost_hoodie_2.jpg',
      'images/products/ghost_hoodie_3.jpg',
    ]
  },
  {
    id: 9,
    name: 'Indian Print Tee',
    collection: 'Drop 01 · Foundation',
    price: 159,
    badge: 'new',
    badgeText: 'New',
    stock: 14,
    sizes: ['XS','S','M','L','XL','XXL'],
    unavail: [],
    category: 'drop01',
    desc: 'South Asian heritage, UAE streets. Bold traditional Indian motif print on heavyweight cotton. A wearable bridge between two homes.',
    fabric: '230gsm 100% ringspun cotton',
    care: 'Cold wash, tumble dry low',
    ph: 'INDIAN\nPRINT',
    color: '#1a0d07',
    img: 'images/products/indian_print_tshirt_1.jpg',
    imgs: [
      'images/products/indian_print_tshirt_1.jpg',
      'images/products/indian_print_tshirt_2.jpg',
    ]
  },
  {
    id: 10,
    name: 'Lips Black Tee',
    collection: 'Drop 01 · Foundation',
    price: 149,
    badge: 'new',
    badgeText: 'New',
    stock: 16,
    sizes: ['XS','S','M','L','XL','XXL'],
    unavail: [],
    category: 'drop01',
    desc: 'Bold. Unapologetic. The lips graphic on a clean black base. 200gsm lightweight cotton, summer-ready cut, relaxed street silhouette.',
    fabric: '200gsm 100% cotton',
    care: 'Machine wash warm, tumble dry',
    ph: 'LIPS\nBLACK',
    color: '#0a0a0a',
    img: 'images/products/lips_black_tshirt_1.jpg',
    imgs: [
      'images/products/lips_black_tshirt_1.jpg',
      'images/products/lips_black_tshirt_2.jpg',
    ]
  },
  {
    id: 11,
    name: 'Lips Tee',
    collection: 'Drop 01 · Foundation',
    price: 149,
    badge: 'new',
    badgeText: 'New',
    stock: 12,
    sizes: ['XS','S','M','L','XL','XXL'],
    unavail: [],
    category: 'drop01',
    desc: 'Same attitude, different canvas. The lips graphic on a lighter colourway. 200gsm cotton, relaxed boxy fit, perfect for the Dubai summer.',
    fabric: '200gsm 100% cotton',
    care: 'Machine wash warm, tumble dry',
    ph: 'LIPS\nTEE',
    color: '#1a1a0a',
    img: 'images/products/lips_tshirt_1.jpg',
    imgs: [
      'images/products/lips_tshirt_1.jpg',
      'images/products/lips_tshirt_2.jpg',
    ]
  },
  {
    id: 12,
    name: 'Punk Hoodie',
    collection: 'Drop 01 · Foundation',
    price: 259,
    badge: 'limited',
    badgeText: 'Limited',
    stock: 6,
    sizes: ['S','M','L','XL','XXL'],
    unavail: [],
    category: 'drop01',
    desc: 'Rebellion has a new postcode. Punk-inspired graphic hoodie with distressed print and raw edge details. Heavy fleece, oversized and unapologetic.',
    fabric: '380gsm cotton/polyester fleece',
    care: 'Cold wash, hang dry',
    ph: 'PUNK\nHOODIE',
    color: '#1a0a14',
    img: 'images/products/punk_hoodie_1.jpg',
    imgs: [
      'images/products/punk_hoodie_1.jpg',
      'images/products/punck_hoodie_2.jpg',
    ]
  },
  {
    id: 13,
    name: 'SAM Logo Tee',
    collection: 'Drop 01 · Foundation',
    price: 139,
    badge: 'new',
    badgeText: 'New',
    stock: 25,
    sizes: ['XS','S','M','L','XL','XXL'],
    unavail: [],
    category: 'drop01',
    desc: 'The original. SAM_Originals logo tee — the piece that started it all. Clean, minimal, essential. 230gsm cotton, the one you wear every week.',
    fabric: '230gsm 100% ringspun cotton',
    care: 'Cold wash, tumble dry low',
    ph: 'SAM\nLOGO',
    color: '#0a0a0a',
    img: 'images/products/sam_logo_tshirt.jpg',
    imgs: [
      'images/products/sam_logo_tshirt.jpg',
    ]
  },
  {
    id: 14,
    name: 'Skull Tee',
    collection: 'Drop 01 · Foundation',
    price: 159,
    badge: 'limited',
    badgeText: 'Limited',
    stock: 7,
    sizes: ['XS','S','M','L','XL','XXL'],
    unavail: ['XS'],
    category: 'drop01',
    desc: 'No fear, no apology. Skull graphic tee with oversized front print. Heavyweight 230gsm cotton, boxy streetwear silhouette, double-stitched throughout.',
    fabric: '230gsm 100% cotton',
    care: 'Cold wash, hang dry',
    ph: 'SKULL\nTEE',
    color: '#111111',
    img: 'images/products/skull_tshirt_1.jpg',
    imgs: [
      'images/products/skull_tshirt_1.jpg',
      'images/products/skull_tshirt_2.jpg',
    ]
  },
  {
    id: 15,
    name: 'Snake Hoodie',
    collection: 'Drop 01 · Foundation',
    price: 269,
    badge: 'limited',
    badgeText: 'Limited',
    stock: 5,
    sizes: ['S','M','L','XL','XXL'],
    unavail: [],
    category: 'drop01',
    desc: 'Shedding what no longer serves you. Snake wrap graphic hoodie with full-back print and embroidered chest logo. The standout piece of Drop 01.',
    fabric: '400gsm cotton/polyester fleece',
    care: 'Cold wash, hang dry, iron inside-out',
    ph: 'SNAKE\nHOODIE',
    color: '#0d1a0a',
    img: 'images/products/snake_hoodie_1.jpg',
    imgs: [
      'images/products/snake_hoodie_1.jpg',
      'images/products/snake_hoodie_2.jpg',
    ]
  },
  {
    id: 16,
    name: 'Essential Tee',
    collection: 'Drop 01 · Foundation',
    price: 129,
    badge: 'new',
    badgeText: 'New',
    stock: 22,
    sizes: ['XS','S','M','L','XL','XXL'],
    unavail: [],
    category: 'drop01',
    desc: 'The foundation piece. Clean SAM_Originals essential tee — no noise, just quality. 230gsm cotton, perfectly cut, built to outlast every trend.',
    fabric: '230gsm 100% ringspun cotton',
    care: 'Cold wash, tumble dry low',
    ph: 'ESSENTIAL\nTEE',
    color: '#141414',
    img: 'images/products/tshirt_1.jpg',
    imgs: [
      'images/products/tshirt_1.jpg',
      'images/products/tshirt_2.jpg',
    ]
  },
  {
    id: 17,
    name: 'WTF Skull Tee',
    collection: 'Drop 01 · Foundation',
    price: 159,
    badge: 'limited',
    badgeText: 'Limited',
    stock: 9,
    sizes: ['XS','S','M','L','XL','XXL'],
    unavail: [],
    category: 'drop01',
    desc: 'Say it with your chest. WTF skull graphic tee — maximum attitude, minimum explanation. Heavyweight 230gsm cotton, oversized boxy cut.',
    fabric: '230gsm 100% cotton',
    care: 'Cold wash, hang dry',
    ph: 'WTF\nSKULL',
    color: '#0d0d0d',
    img: 'images/products/wtf_skull_tshirt_1.jpg',
    imgs: [
      'images/products/wtf_skull_tshirt_1.jpg',
      'images/products/wtf_skull_tshirt_2.jpg',
    ]
  },
];